export const categories = [
  "History",
  "Science: Computers",
  "Entertainment: Video Games",
  "Mythology",
  "Entertainment: Television",
  "General Knowledge",
  "Entertainment: Music",
  "Animals",
  "Geography",
  "Art",
  "Celebrities",
  "Science & Nature",
  "Vehicles",
  "Politics",
  "Sports",
];
