export const categories = [
  { id: 23, name: "History" },
  { id: 18, name: "Science: Computers" },
  { id: 15, name: "Entertainment: Video Games" },
  { id: 20, name: "Mythology" },
  { id: 14, name: "Entertainment: Television" },
  { id: 9, name: "General Knowledge" },
  { id: 12, name: "Entertainment: Music" },
  { id: 27, name: "Animals" },
  { id: 22, name: "Geography" },
  { id: 25, name: "Art" },
  { id: 26, name: "Celebrities" },
  { id: 17, name: "Science & Nature" },
  { id: 28, name: "Vehicles" },
  { id: 24, name: "Politics" },
  { id: 21, name: "Sports" },
];
